(async function () {
  if (!window.BattleEffects) window.BattleEffects = { showWave(scene, n) { const label=scene.add.text(-180,GAME_H/2,`WAVE ${n}`,{fontFamily:'Arial Black',fontSize:'64px',color:'#fff5bd',stroke:'#253340',strokeThickness:12}).setOrigin(.5).setDepth(20);scene.tweens.add({targets:label,x:GAME_W/2,duration:520,ease:'Cubic.out',onComplete:()=>scene.tweens.add({targets:label,scale:1.28,duration:220,hold:500,onComplete:()=>scene.tweens.add({targets:label,x:GAME_W+180,duration:520,ease:'Cubic.in',onComplete:()=>label.destroy()})})}); } };
  let data; try { data = await fetch('stages.json').then(r => r.json()); } catch (_) { return; }
  const stage = data.stages.find(s => s.id === 1), flatten = w => w.enemies.flatMap(g => Array(g.count).fill(g.type));
  const timer = setInterval(() => {
    const s = game.scene.getScene('Battle'); if (!s || !s.sys.isActive()) return;
    clearInterval(timer); let pending = [], wave = 0, clear = false; const inheritedSpawn = s.spawnEnemy.bind(s), inheritedUpdate = s.update.bind(s);
    const hud = () => document.querySelector('#wave-value').textContent = `STAGE 1 · ${wave + 1} / ${stage.waves.length}`; hud();
    s.spawnEnemy = function () { const type = pending.shift(); if (!type) return; inheritedSpawn(); const e = this.enemies.at(-1), d = data.monsterTypes[type]; e.kind=type; e.maxHp=e.hp=d.hp; e.speed=d.speed*2; e.autoDamageMultiplier=d.autoDamageMultiplier; e.strongDamageMultiplier=d.strongDamageMultiplier; e.body.setRadius(d.radius).setFillStyle(Number(d.color)); };
    s.startWave = function () { if (state.waveActive || clear) return; pending=flatten(stage.waves[wave]); state.waveActive=true; this.spawned=0; if(window.BattleEffects) BattleEffects.showWave(this,wave+1); this.status.setText(`${stage.name} · 웨이브 ${wave+1}`); this.spawner=this.time.addEvent({delay:500,repeat:pending.length-1,callback:()=>this.spawnEnemy()}); };
    s.moveShot = function (shot, delta) { if(!this.enemies.includes(shot.target)){shot.dot.destroy();this.shots.splice(this.shots.indexOf(shot),1);return;} const a=Phaser.Math.Angle.Between(shot.x,shot.y,shot.target.body.x,shot.target.body.y), step=460*delta/1000;shot.x+=Math.cos(a)*step;shot.y+=Math.sin(a)*step;shot.dot.setPosition(shot.x,shot.y);if(Phaser.Math.Distance.Between(shot.x,shot.y,shot.target.body.x,shot.target.body.y)<shot.target.body.radius+3){shot.target.hp-=shot.damage*(shot.target.autoDamageMultiplier??1);shot.dot.destroy();this.shots.splice(this.shots.indexOf(shot),1);if(shot.target.hp<=0){this.removeEnemy(shot.target);state.gold+=10;syncHud();hud();}} };
    s.performStrongAttack = function () { if(!this.enemies.length){this.status.setText('강공을 가할 적이 없습니다');return;}const t=[...this.enemies].sort((a,b)=>b.body.x-a.body.x)[0],damage=48*(t.strongDamageMultiplier??1);t.hp-=damage;const hit=this.add.text(t.body.x,t.body.y-34,`-${Math.round(damage)}`,{fontFamily:'Arial Black',fontSize:'20px',color:'#fff2a0',stroke:'#5a250e',strokeThickness:4}).setOrigin(.5).setDepth(10);this.tweens.add({targets:hit,y:hit.y-28,alpha:0,duration:450,onComplete:()=>hit.destroy()});if(t.hp<=0){this.removeEnemy(t);state.gold+=15;syncHud();hud();} };
    s.update = function (time,delta) { inheritedUpdate(time,delta); if(state.waveActive&&pending.length===0&&this.enemies.length===0&&this.spawned>0){state.waveActive=false;wave++;if(wave>=stage.waves.length){clear=true;this.status.setText('STAGE 1 CLEAR! 다음 스테이지는 stages.json에 추가할 수 있습니다.');document.querySelector('#wave-button').disabled=true;document.querySelector('#wave-value').textContent='STAGE 1 CLEAR';}else{hud();document.querySelector('#wave-button').disabled=false;}} };
    let strongButton=document.querySelector('#strong-attack-button');if(!strongButton){strongButton=document.createElement('button');strongButton.id='strong-attack-button';strongButton.className='strong-button';strongButton.textContent='강공 ✦';document.querySelector('#wave-button')?.before(strongButton);}
    strongButton.addEventListener('click',()=>s.performStrongAttack()); window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();s.performStrongAttack();}});
  },50);
}());
